services:
  kc_postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak_net

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.2
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: kc_postgres   
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
    ports:
      - "8081:8080"
    depends_on:
      - kc_postgres
    networks:
      - keycloak_net
  
  backend:
    build:
      context: ./Back-end
      dockerfile: Dockerfile.backend
    env_file:
      - ./Back-end/.env.local
    ports:
      - "5000:5000"
    depends_on:
      - database_local
    networks:
      - backend

  database_local:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres        
      POSTGRES_PASSWORD: Laureano    
      POSTGRES_DB: quoter 
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend
    
volumes:
  postgres_data:
  pgdata:
networks:
  keycloak_net:
    driver: bridge
  backend:
    driver: bridge
